-- TRANSACTION EXAMPLE FOR PATS DATABASE
--
-- by (student_1) & (student_2)
--
--
-- Zaphod (pet id: 173; owned by Horacio Mayert) the dog comes in today for a visit and weighs 39 pounds.
-- Zaphod gets an examination because he's lost some weight unexpectedly. (Last two visits he weighed 48 and 50 pounds, so 39 pounds is low for Zaphod.)
-- Assuming the required 500 units are in stock and the medicine is appropriate for a dog, Zaphod is given Ivermectin (medicine id: 3) to treat a nasty parasite which is responsible for the weight loss.
-- Assuming the required 200 units are in stock and the medicine is appropriate for a dog, Zaphod is given Mirtazapine (medicine id: 5) to stimulate his appetite and help get his weight back up to the 50 pound range.
-- Assuming no problems, then total costs for these services and medicines are calculated (no discounts for Horacio), the overnight_stay flag is evaluated and all the data is committed to the database. If there are any problems at any step, then none of this data is saved to the system.